package mpdr.tapis.oracle;

import mpdr.tapis.interfaces.IMPDRDynamicCodeType;

public enum MPDROracleDynamicCodeType implements IMPDRDynamicCodeType {
    TRIGGER_NEW_TO_RECORD("TRIGGER_NEW_TO_RECORD", "" ),
    TRIGGER_OLD_TO_RECORD("TRIGGER_OLD_TO_RECORD", "" ),
    TRIGGER_RECORD_TO_NEW("TRIGGER_RECORD_TO_NEW", "" ),
    TABLE_DEP_JOIN_PARENT("TABLE_DEP_JOIN_PARENT", "" ),
    ASSNN_REF_NONORIENTED_COLFIRST("ASSNN_REF_NONORIENTED_COLFIRST", "" ),
    ASSNN_REF_NONORIENTED_COLSECOND("ASSNN_REF_NONORIENTED_COLSECOND", "" ),
    COLUMNS_TO_GENERALIZE("COLUMNS_TO_GENERALIZE", ""),
    COLUMNS_TO_SPECIALIZE("COLUMNS_TO_SPECIALIZE", ""),
    ASS11_NONORIENTED_PKFIRST("ASS11_NONORIENTED_PKFIRST", ""),
    ASS11_NONORIENTED_FKFIRST("ASS11_NONORIENTED_FKFIRST", ""),
    ASS11_FKNOTNULL("ASS11_FKNOTNULL",""),
    IOINS_ASSNNNONORIENTED_WHERE("IOINS_ASSNNNONORIENTED_WHERE",""),
    IODEL_ASSNNNONORIENTED_WHERE_CROSSEDPAIR("IODEL_ASSNNNONORIENTED_WHERE_CROSSEDPAIR",""),
    IODEL_ASSNNNONORIENTED_WHERE_NOTCROSSEDPAIR("IODEL_ASSNNNONORIENTED_WHERE_NOTCROSSEDPAIR",""),
    IO_ASSNNNONORIENTED_UPDATE_COLUMNS("IO_ASSNNNONORIENTED_UPDATE_COLUMNS", ""),
    //WRITE_TABLE_FROZEN_NONAUTHORIZED("WRITE_TABLE_FROZEN_NONAUTHORIZED", ""),
    LIST_COLUMNS("LIST_COLUMNS", ""),
    LIST_COLUMNS_NEWS("LIST_COLUMNS_NEWS", ""),
    COLUMNS_UPPERCASE("COLUMNS_UPPERCASE", ""),
    COLUMNS_TYPE_CHECK("COLUMNS_TYPE_CHECK", ""),
    COLUMNS_FROZEN("COLUMNS_FROZEN", ""),
    COLUMNS_PEA("COLUMNS_PEA",""),
    COLUMN_TARGET_LIEN_PROG("COLUMN_TARGET_LIEN_PROG",""),
    ALL_COLUMNS_NAME("ALL_COLUMNS_NAME", ""),
    ALL_COLUMNS_VALUE("ALL_COLUMNS_VALUE", ""),
    PK_COLUMNS_NAME("PK_COLUMNS_NAME", ""),
    PK_COLUMNS_VALUE("PK_COLUMNS_VALUE", ""),
    JN_COLUMNS_NAME("JN_COLUMNS_NAME", ""),
    JN_COLUMNS_VALUE("JN_COLUMNS_VALUE", ""),
    INS_JN_INS("INS_JN_INS",""),
    INS_JN_UPD("INS_JN_UPD",""),
    INS_JN_DEL("INS_JN_DEL",""),
    ORDERED_INS("ORDERED_INS",""),
    COLUMN_DEFAULT_VALUE("COLUMN_DEFAULT_VALUE", "");


    private java.lang.String key;
    private java.lang.String value;


    private MPDROracleDynamicCodeType(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public String getKey() {
        return this.key;
    }

    public String getValue() {
        return this.value;
    }

    public  MPDROracleDynamicCodeType[] getAll() {
        return values();
    }

}
