package window.editor.diagrammer.utils;

public enum Position {
  TOP_RIGHT, TOP_LEFT, BOTTOM_RIGHT, BOTTOM_LEFT, TOP_CENTER_LEFT, TOP_CENTER_RIGHT, BOTTOM_CENTER_LEFT, BOTTOM_CENTER_RIGHT, LEFT_TOP, LEFT_BOTTOM, RIGHT_TOP, RIGHT_BOTTOM, UNHANDLED
}
